### ISSUE TITLE
devops_ansible and devops_gha_deploy questions make no sense

### ISSUE THREAD

**Issue by fredvd** [collective/cookiecutter-plone-starter#103]
When I run cookiecutter for this template and download the latest version, the 2 questions for devops_ansible and devops_gha_deploy make no sense on the console output. Only a 1 or 0 is listes for chcoices 1 and 2.....

```
Select container_registry:
1 - GitHub
2 - Docker Hub
Choose from 1, 2 [1]: 1
Select devops_ansible:
1 - 1
2 - 0
Choose from 1, 2 [1]: 1
Select devops_gha_deploy:
1 - 1
2 - 0
Choose from 1, 2 [1]: 1
```

**Comment by davisagli** [comment]
@fredvd Upgrade cookiecutter; you're supposed to be getting more helpful prompts.

**Comment by fredvd** [comment]
Confirmed it was an older cookiecutter. I was absolutely sure I had updated cookiecutter itself  .... I did on another machine.  The templates itself are freshly downloaded.
