### ISSUE TITLE
Should default versions installed by the cookiecutter be alphas?

### ISSUE THREAD

**Issue by stevepiercy** [collective/cookiecutter-plone-starter#109]
Should the default version of Volto (or any other package installed by the cookiecutter) be a stable release or an alpha release? @ericof @davisagli @ksuess @jensens @sneridagh @fosten @fredvd @mauritsvanrees

See https://github.com/plone/documentation/pull/1574#discussion_r1386402220

**Comment by ericof** [comment]
No, they should not.
It made sense when we were close to releasing 17.0, but now we should revert that.

**Comment by sneridagh** [comment]
I agree. I foresee that from now on alphas will be more breaking than before, so we should encourage people to use "current stable"

**Comment by ericof** [comment]
@stevepiercy I will close because the default version, for now, is 17.x (the stable version)
