### ISSUE TITLE
add pnpm support

### ISSUE THREAD

**Issue by animus888** [collective/cookiecutter-plone-starter#115]
Will there be an option for using pnpm as package manager for volto projects in future?
--> https://github.com/plone/volto/blob/0fcacc2a937002079d3e1bbf7be7eccf4e453468/packages/volto/CHANGELOG.md?plain=1#L50C1-L50C80

**Comment by stevepiercy** [comment]
Yes, it will be preferred in Volto 18, and is recommended now for installation for contributing to Volto. https://6.docs.plone.org/volto/contributing/developing-core.html?highlight=pnpm

**Comment by animus888** [comment]
alright, so I look forward to Volto 18 becoming a release version. :+1:
