### ISSUE TITLE
Use cookiecutter-zope-instance

### ISSUE THREAD

**Issue by jensens** [collective/cookiecutter-plone-starter#122]
[cookiecutter-zope-instance](https://github.com/plone/cookiecutter-zope-instance) handles almost all aspects of configuring a Zope instance. It does not make sense to do the same in here in a reduced form.

**Comment by davisagli** [comment]
@jensens cookiecutter-zope-instance is already used: https://github.com/collective/cookiecutter-plone-starter/blob/bdc19e50e27a177c93f7c92c705f569013b99fea/%7B%7B%20cookiecutter.project_slug%20%7D%7D/backend/Makefile#L95 -- so what did you have in mind?

**Comment by jensens** [comment]
huh, wait, let me close this and go back to the drawing board.
