### ISSUE TITLE
semver not available in runtime environment, reverted #129

### ISSUE THREAD

**Issue by fredvd** [collective/cookiecutter-plone-starter#131]
@ericof You merged https://github.com/collective/cookiecutter-plone-starter/pull/129  , but semver is not available on runtime. @sneridagh Tried to fix this by using a hook install semver, but couldn't get it working, so I reverted the change for now. 

The tests didn't catch this because they are using the requirement.txt to install semver, this does not happen when I call the template from a locally installed cookiecutter.  Trying a hook to install it using pipx assumes / binds the template to using pipx always, but this doesn't have to be the case. 

The most straightforward solution would imho be to make semver a dependency of cookiecutter itself and give it a new release.  But cookiecutter seems to be lean on (no?) dependencies itself.

**Comment by davisagli** [comment]
Fixed in #132
