### ISSUE TITLE
Use plone.api instead of kitconcept.api

### ISSUE THREAD

**Issue by davisagli** [collective/cookiecutter-plone-starter#16]
(This might require moving some features from kitconcept.api to plone.api, like extra parameters for api.user.create)

**Comment by jensens** [comment]
relates to #20 - Plone CLI does not use it

**Comment by ericof** [comment]
I would keep it here until we move the features to `plone.api`.

**Comment by jensens** [comment]
No, in an officially supported package we can not use company namespaces, sorry.

**Comment by davisagli** [comment]
Moving any necessary features to plone.api is exactly what I was trying to say with this ticket.

**Comment by jensens** [comment]
We already have 
https://docs.plone.org/develop/plone.api/docs/api/user.html#plone.api.user.create
