### ISSUE TITLE
Cannot `make install`

### ISSUE THREAD

**Issue by stevepiercy** [collective/cookiecutter-plone-starter#38]
After creating a project with `cookiecutter gh:collective/cookiecutter-plone-starter`, I try `make install`. It proceeds to install the backend successfully, then tries to install the frontend, but eventually fails.

```
warning "@storybook/react > @storybook/core > @storybook/core-server > @storybook/builder-webpack4@6.5.13" has unmet peer dependency "react-dom@^16.8.0 || ^17.0.0 || ^18.0.0".
[5/5] 🔨  Building fresh packages...
[7/7] ⠄ @plone/volto
[-/7] ⡀ waiting...
[-/7] ⡀ waiting...
[-/7] ⡀ waiting...
error /Users/stevepiercy/projects/plone-conference/frontend/node_modules/@plone/volto: Command failed.
Exit code: 1
Command: yarn patches
Arguments: 
Directory: /Users/stevepiercy/projects/plone-conference/frontend/node_modules/@plone/volto
Output:
Usage Error: The nearest package directory (/Users/stevepiercy/projects/plone-conference/frontend/node_modules/@plone/volto) doesn't seem to be part of the project declared in /Users/stevepiercy/projects/plone-conference/frontend.

- If /Users/stevepiercy/projects/plone-conference/frontend isn't intended to be a project, remove any yarn.lock and/or package.json file there.
- If /Users/stevepiercy/projects/plone-conference/frontend is intended to be a project, it might be that you forgot to list node_modules/@plone/volto in its workspace configuration.




make[2]: *** [install] Error 1
make[1]: *** [install-frontend] Error 2
make: *** [install] Error 2
```

## Summary:
- Plone version: 6.0.0b3
- Volto version: 16.0.0-alpha.49

**Comment by sneridagh** [comment]
@stevepiercy it should work with latest V16a50. 

@ericof @jensens Hesitating if force latest @plone/generator-volto alpha in the install, since we'll have to undo the change after we release the final.

**Comment by ericof** [comment]
@sneridagh I will work on that today (as we also need to fix Makefile and Dockerfile) for the latest Volto release to work.

**Comment by sneridagh** [comment]
@stevepiercy @ericof @jensens https://github.com/collective/cookiecutter-plone-starter/pull/39

**Comment by sneridagh** [comment]
@ericof just saw your comment, then `Dockerfile` and `Makefile` amendments are due.

**Comment by stevepiercy** [comment]
OK, I am also watching #40. Please let me know when I should try it out to confirm all works as intended. Thank you!

**Comment by stevepiercy** [comment]
Let's do two more merges while we are at it before I test.

- https://github.com/collective/cookiecutter-plone-starter/pull/37
- https://github.com/plone/training/pull/694

**Comment by stevepiercy** [comment]
Looking good so far:

```console
Summary:
  - Plone version: 6.0.0b3
  - Volto version: 16.0.0-alpha.50
  - Volto Generator version: 6.0.0-alpha.3
  - Output folder: /Users/stevepiercy/projects/plone-conference
```

...and `make install` got through frontend install. Closing.

I might refine the Training docs further. Thank you!
