### ISSUE TITLE
Backend and frontend `make build-image` fails with invalid Dockerfile syntax

### ISSUE THREAD

**Issue by kenmanheimer** [collective/cookiecutter-plone-starter#54]
Trying to build the backend or frontend Docker images fails because the “here”-style syntax used with the Dockerfile RUN command does not work correctly in the most recent available Docker version. For instance, these ["RUN <<EOT ..."](https://github.com/collective/cookiecutter-plone-starter/blob/main/%7B%7B%20cookiecutter.project_slug%20%7D%7D/backend/Dockerfile#L14-L20) lines in the backend Dockerfile fail like this:

```json
make build-image
+ which python3
+ python3 -c 'import sys; print((int(sys.version_info[0]), int(sys.version_info[1])) >= tuple(map(int, '\''3.8'\''.split('\''.'\''))))'
+ docker build . -t kenmanheimer/myr-plone-backend:latest -f Dockerfile --build-arg PLONE_VERSION=6.0.0
Sending build context to Docker daemon  2.483MB
Error response from daemon: dockerfile parse error line 15: unknown instruction: ./BIN/PIP
make: *** [Makefile:166: build-image] Error 1
```

A similar failure happens with similar syntax in the frontend Dockerfile [here](https://github.com/collective/cookiecutter-plone-starter/blob/main/%7B%7B%20cookiecutter.project_slug%20%7D%7D/frontend/Dockerfile.default#L5-L10), [here](https://github.com/collective/cookiecutter-plone-starter/blob/main/%7B%7B%20cookiecutter.project_slug%20%7D%7D/frontend/Dockerfile.default#L17-L20), and [here](https://github.com/collective/cookiecutter-plone-starter/blob/main/%7B%7B%20cookiecutter.project_slug%20%7D%7D/frontend/Dockerfile.default#L29-L35).

Maybe the `here` syntax works on the version of Docker on someone’s system, but it does not work on the most recent version of Docker available for my Ubuntu 20.04 or Ubuntu 22.04 systems, Docker version 20.10.22 build 3a2c30b.

A solution that should work on recent Docker versions is to instead use continuation lines separated by `&&` command list operators, as is done with the LABEL statement elsewhere in both Dockerfiles, and typically with the RUN command in many Docker files.

I will file a pull request next.

**Comment by davisagli** [comment]
Ah, it looks like the heredoc feature is supported when building using buildkit / docker buildx, but not when building in the way that is the default on linux. I didn't realize that. I guess we should stick with the syntax that is more broadly compatible. /cc @jensens

**Comment by jensens** [comment]
Well buildx is IMO the way to go, for more than just syntax. So, we just need to change the Makefile where not adopted already.

**Comment by kenmanheimer** [comment]
Just switching the command from `docker build ...` to `docker buildx build ...` doesn't work. I realize that time is limited, but just to be clear, for `make build-image` to work either that solution or the one for which I provided a pull request still is pending implementation.

**Comment by jensens** [comment]
@kenmanheimer it works if the header statement `# syntax=docker/dockerfile:1` is included and docker buildkit is used.
see https://docs.docker.com/engine/reference/builder/#syntax and referenced buildkit docs. 
`buildx` always uses buildkit.
