### ISSUE TITLE
Unrecognized named-value: 'is_default_branch' in `.github/workflows/frontend.yml`

### ISSUE THREAD

**Issue by Fosten** [collective/cookiecutter-plone-starter#62]
This change broke the GHA builds
https://github.com/collective/cookiecutter-plone-starter/commit/43d25ccd68e7b47bb35c344c6a96cee5485c0f81
Changing the results of the project_slug from
type=raw,value=latest,enable=${{ is_default_branch }}
to
type=raw,value=latest,enable={{ is_default_branch }}
fixed the issue for me.

**Comment by stevepiercy** [comment]
Which builds broke?

https://github.com/collective/cookiecutter-plone-starter/actions

**Comment by Fosten** [comment]
Clarification: it broke the resulting project_slug's GHA builds, not this repo's GHA builds.

**Comment by stevepiercy** [comment]
I don't know whether we can run CI inside of CI. That would be a nifty trick.

Anyway, you "fixed" the rendered project files, not the cookiecutter templates, and even then I don't think it was actually fixed. GHA will set `enable` to the literal string `{{ is_default_branch }}` as a tag for the Docker image.

```
type=raw,value=latest,enable={{ is_default_branch }}
```

I'm not sure what the intent is for this, but here is the documentation for adding a tag.

https://github.com/docker/metadata-action#typeraw

@ericof @jensens anyone else know?
