### ISSUE TITLE
i18n sync error

### ISSUE THREAD

**Issue by Fosten** [collective/cookiecutter-plone-starter#63]
Frontend GHA build fails with i18n sync error on first run.

After running the command 'make i18n' and pushing the new volto.po files to a repo, GHA builds successfully.

This is required to update the "POT-Creation-Date: 2023-02-13T23:02:51.976Z\n" timestamps.

**Comment by stevepiercy** [comment]
Can this be automated? If not, then documenting the process would be the best course of action.

**Comment by ericof** [comment]
Imo, this should be a pre-commit hook.

**Comment by stevepiercy** [comment]
pre-commit works for me. However we need to ensure that it is either installed by the cookiecutter or specified as a pre-requisite in the documentation.
