### ISSUE TITLE
Accept Podman as an alternative to Docker

### ISSUE THREAD

**Issue by ju55i** [collective/cookiecutter-plone-starter#92]
It would be nice if Podman would be recognized as an alternative to Docker. Any business use of Docker would require a paid license. Podman already kind of works with cookiecutter-plone-starter if the podman binary is symlinked as docker. Sanity check will complain about the version but will proceed anyway.

**Comment by stevepiercy** [comment]
See [Containers](https://6.docs.plone.org/install/index.html#containers).

If you would like to contribute instructions for how to use podman instead of Docker to the documentation, I would be open to it. However, note that Docker is used for more than just project generation. Maybe your instructions will give podman some traction?

FWIW, I share your licensing concern.

**Comment by ju55i** [comment]
I'm trying to use make build-images with Podman and heredoc format causes currently [problems](https://github.com/containers/buildah/issues/3474).

**Comment by ju55i** [comment]
I didn't experience anything else broken with Podman except using the podman binary as the docker command and the heredoc formating in the Dockerfiles.

**Comment by stevepiercy** [comment]
One more thing, I have a plan to slowly organize documentation following the [Diátaxis framework](https://diataxis.fr/). We have tutorials via Trainings, and lots of explanation and reference, but only a smattering of how-to guides scattered to the four winds. This topic would be an excellent how-to guide. If you write up something for documentation, your contribution could be the first how-to guide.

See https://6.docs.plone.org/contributing/documentation/index.html for details of how to contribute.

**Comment by davisagli** [comment]
Podman added support for heredoc syntax in Dockerfiles. `make build-images` seems to be working for me with /usr/local/bin/docker symlinked to podman.
